Repository caldasluan/meau, pull requests merged in 2019-05, with the labels that each got.

#4 Implementar classe UserModel.java
  app/src/main/java/com/dap/meau/Model/UserModel.java
Labels: enhancement, work in progress

#7 Hotfix perfil animal
  app/src/main/java/com/dap/meau/PerfilAnimal.java
  app/src/main/res/layout/activity_perfil_animal.xml
  app/src/main/res/values/strings.xml
Labels: bug

#8 Corrigir posição do botão cad_animal_btn_colocarAdocao em activity_cadastro_animal.xml
  app/src/main/res/layout/activity_cadastro_animal.xml
Labels: bug

#9 Consertar botão "Cadastrar Animal" em InitActivity.java
  app/src/main/java/com/dap/meau/InitActivity.java
  app/src/main/res/layout/activity_init.xml
Labels: bug

#2 Adicionar tela de Cadastro Pessoal
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
  app/src/main/res/layout/activity_cadastro_pessoal.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#10 Criação e correção das classes de dados e seus atributos
  .idea/misc.xml
  app/src/main/java/com/dap/meau/Model/PetModel.java
  app/src/main/java/com/dap/meau/Model/PetUserInterestModel.java
  app/src/main/java/com/dap/meau/Model/UserModel.java
Labels: enhancement, work in progress

#22 Criar ErroSessaoActivity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dap/meau/ErroSessaoActivity.java
  app/src/main/res/layout/activity_erro_sessao.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#29 Consertar aviso de Usuário Logado
  app/src/main/java/com/dap/meau/LoginActivity.java
Labels: bug

#30 Atualizar InitActivity.java com botão "Sair"
  app/src/main/java/com/dap/meau/InitActivity.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#17 Criar método para pesquisar usuário por email
  app/src/main/java/com/dap/meau/Helper/DatabaseFirebase/UserDatabaseHelper.java
Labels: enhancement

#36 Remover arquivos e recursos desnecessários
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/meau_malha.png
  app/src/main/res/layout/header_drawer_main.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_field_styles.xml
Labels: enhancement

#43 Consertar login do google em CadastroPessoalActivity.java
  app/google-services.json
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
Labels: bug

#39 ShortName agora é preenchido com nome e sobrenome do usuário
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
Labels: feature/polimento

#47 Fix #44: Atualizar InitActivity.java para mostrar notificação de logout
  app/src/main/java/com/dap/meau/InitActivity.java
Labels: bug

#46 Atualizar AcceptActivityAdapter.java mudando FullName para ShortName
  app/src/main/java/com/dap/meau/Adapter/AcceptActivityAdapter.java
Labels: feature/polimento

#40 Fix #34: Consertar opções do drawer em InitActivity.java
  app/src/main/java/com/dap/meau/InitActivity.java
  app/src/main/java/com/dap/meau/MainActivity.java
  app/src/main/res/menu/menu_drawer_main.xml
Labels: discussão, feature/polimento

#53 Fix #35: Remover botões não utilizados na drawer
  app/src/main/res/menu/menu_drawer_main.xml
Labels: feature/polimento

#49 Fix #31: Aprimorar lista de animais para adoção
  app/src/main/java/com/dap/meau/ui/main/MainFragment.java
Labels: feature/polimento

#54 Fix #50: O usuário deve decidir se o animal fica disponível para adoção
  .idea/gradle.xml
  app/src/main/java/com/dap/meau/Adapter/MyPetsFragmentAdapter.java
  app/src/main/java/com/dap/meau/CadastroAnimalActivity.java
  app/src/main/java/com/dap/meau/Model/PetModel.java
  app/src/main/java/com/dap/meau/PerfilAnimal.java
  app/src/main/java/com/dap/meau/ui/main/MainFragment.java
  app/src/main/res/layout/activity_perfil_animal.xml
  app/src/main/res/values/strings.xml
Labels: feature/polimento

#56 Esconder animais indisponíveis da lista de adoção
  app/src/main/java/com/dap/meau/ui/main/MainFragment.java
Labels: bug

#60 Atualizar estilo dos botões de acordo com o tema do app
  app/src/main/res/layout/activity_perfil_animal.xml
Labels: feature/polimento

#62 Retornar o usuário para "Meus pets" após uma adoção
  app/src/main/java/com/dap/meau/Adapter/AcceptActivityAdapter.java
  app/src/main/java/com/dap/meau/PerfilAnimal.java
Labels: bug, feature/polimento

#61 Definir animal como indisponível na conclusão de uma adoção
  app/src/main/java/com/dap/meau/Adapter/AcceptActivityAdapter.java
Labels: bug, feature/polimento

#64 Atualizar ícone de notificação
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dap/meau/Service/MessageService.java
  app/src/main/res/drawable-hdpi/ic_stat_notification_icon.png
  app/src/main/res/drawable-mdpi/ic_stat_notification_icon.png
  app/src/main/res/drawable-xhdpi/ic_stat_notification_icon.png
  app/src/main/res/drawable-xxhdpi/ic_stat_notification_icon.png
  app/src/main/res/drawable-xxxhdpi/ic_stat_notification_icon.png
Labels: bug

#65 Implementar a adição de fotos da câmera ou galeria para perfis
  .idea/gradle.xml
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dap/meau/CadastroAnimalActivity.java
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
  app/src/main/res/layout/activity_cadastro_animal.xml
  app/src/main/res/layout/activity_cadastro_pessoal.xml
  app/src/main/res/values/strings.xml
Labels: atenção, feature/polimento

#66 Conserta pequenos erros na UI de várias telas
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
  app/src/main/java/com/dap/meau/ErroSessaoActivity.java
  app/src/main/res/layout/activity_cadastro_animal.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_perfil_animal.xml
  app/src/main/res/values/button_styles.xml
Labels: feature/polimento

#67 Fix #33: Atualizar drawer em InitActivity.java na saída do usuário
  app/src/main/java/com/dap/meau/InitActivity.java
Labels: bug, feature/polimento

#71 Arrumar a localização dos animais
  app/src/main/java/com/dap/meau/Adapter/AcceptActivityAdapter.java
  app/src/main/java/com/dap/meau/CadastroAnimalActivity.java
Labels: feature/polimento

#73 Fix #72: Arrumar shortname quando usuario só tem um nome
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
Labels: feature/polimento

#74 Tornar drawer mais amigável e prevenir falhas no login
  app/src/main/java/com/dap/meau/LoginActivity.java
  app/src/main/res/drawable/ic_add_circle_outline_black_24dp.xml
  app/src/main/res/drawable/ic_insert_emoticon_black_24dp.xml
  app/src/main/res/drawable/ic_stars_black_24dp.xml
  app/src/main/res/drawable/nav_header_bg.xml
  app/src/main/res/layout/nav_header_menu.xml
  app/src/main/res/menu/menu_drawer_main.xml
Labels: bug, feature/polimento

#75 Adiciona ScrollView pai em InitActivity.java
  app/src/main/java/com/dap/meau/InitActivity.java
  app/src/main/res/layout/activity_init.xml
  app/src/main/res/values/styles.xml
Labels: bug, feature/polimento

#76 Consertar margens do layout em activity_perfil_animal.xml
  app/src/main/res/layout/activity_perfil_animal.xml
Labels: bug

#77 Carregar a foto de perfil do google na interface de selecionar a foto de usuário
  app/src/main/java/com/dap/meau/CadastroPessoalActivity.java
Labels: feature/polimento

#78 Mostrar mensagem de erro em lista vazia
  app/src/main/java/com/dap/meau/AcceptActivity.java
  app/src/main/java/com/dap/meau/ui/main/MainFragment.java
  app/src/main/java/com/dap/meau/ui/main/MyPetsFragment.java
  app/src/main/res/layout/activity_accept.xml
  app/src/main/res/layout/fragment_my_pets.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/values/strings.xml
Labels: bug, confirmado

#79 Alinhar posições de views em activity_init.xml
  app/src/main/res/layout/activity_init.xml
Labels: feature/polimento

#80 Guardar as Fragments na pilha de retorno
  app/src/main/java/com/dap/meau/MainActivity.java
Labels: feature/polimento
